[package]
name = "Durhack24"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.214", features = ["derive"]}
calamine = "0.26.1"
warp = "0.3"
tokio = { version = "1", features = ["full"] }

